# Download test data from: https://osf.io/8jz7e/
#model_path: /homedtic/dvarela/pretrained/pytunet3D/models/best_checkpoint_confocal_boundary.pytorch
model_path: /homedtic/dvarela/pretrained/pytunet3D/models/best_checkpoint_PNAS_plantseg.pytorch
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
  is_segmentation: true
predictor:
  name: 'StandardPredictor'
loaders:
  # save predictions to output_dir
  output_dir: /homedtic/dvarela/CROPS/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  mirror_padding: [16, 32, 32]
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    file_paths:
      - /homedtic/dvarela/CardiacRegion/all/mem/20190209_E2_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190308_E3_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190503_E2_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190516_E3_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190521_E1_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190523_E1_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190806_E3_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190806_E4_mGFP_CardiacRegion_0.5_ZXY.h5
      - /homedtic/dvarela/CardiacRegion/all/mem/20190806_E6_mGFP_CardiacRegion_0.5_ZXY.h5

      
    slice_builder:
      name: SliceBuilder
      patch_shape: [80, 170, 170]
      stride_shape: [40, 90, 90]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true